version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: boilerplate_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.api.production
    depends_on:
      - mongodb
      - redis
    networks:
      - boilerplate_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🆕 NOVO SERVIÇO: Worker Container
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    env_file:
      - .env.worker.production
    depends_on:
      - mongodb
      - redis
    networks:
      - boilerplate_network
    deploy:
      replicas: 1 # 🆕 1 replica por padrão
      resources:
        limits:
          cpus: "0.8"
          memory: 768M
        reservations:
          cpus: "0.3"
          memory: 256M
    healthcheck:
      test:
        ["CMD", "node", "-e", "console.log('Worker health'); process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongodb:
    image: mongo:latest
    container_name: boilerplate_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: boilerplate
    volumes:
      - mongodb_data:/data/db
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    container_name: boilerplate_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - boilerplate_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
  redis_data:
  minio_data:

networks:
  boilerplate_network:
    driver: bridge
