version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - redis
    networks:
      - boilerplate_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: boilerplate_queue_worker
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - redis
    networks:
      - boilerplate_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "pgrep", "-f", "queue.worker.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongodb:
    image: mongo:latest
    container_name: boilerplate_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: boilerplate
    volumes:
      - mongodb_data:/data/db
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    container_name: boilerplate_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
  redis_data:

networks:
  boilerplate_network:
    driver: bridge
