version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: boilerplate_app_dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.api.development
    depends_on:
      - mongodb
      - redis
      - postgres
    networks:
      - boilerplate_network
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🆕 NOVO SERVIÇO: Worker Development
  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.worker.development
    depends_on:
      - mongodb
      - redis
      - postgres
    networks:
      - boilerplate_network
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run worker:dev # 🆕 Comando específico para worker
    deploy:
      replicas: 1 # 🆕 1 replica por padrão
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "console.log('Worker dev health'); process.exit(0)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongodb:
    image: mongo:latest
    container_name: boilerplate_mongodb_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: boilerplate
    volumes:
      - mongodb_data:/data/db
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    container_name: boilerplate_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PostgreSQL with pgvector extension for vector embeddings
  postgres:
    image: pgvector/pgvector:pg16
    container_name: boilerplate_postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boilerplate_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Services container for development
  # BullMq Dashboard
  bull-board:
    build:
      context: ./bullDashboard
      dockerfile: Dockerfile
    container_name: bull-dashboard
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis # O nome do serviço Redis no Compose
    networks:
      - boilerplate_network
    depends_on:
      - redis

  # Fake email server smtp for send email and dashboard for visualize emails
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # Porta SMTP - a mesma que você usa no Nodemailer
      - "8025:8025" # Porta da Interface Web - acesse http://localhost:8025
    restart: unless-stopped
    networks:
      - boilerplate_network

  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio_dev
    restart: unless-stopped
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - boilerplate_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
  redis_data:
  postgres_data:
  mailhog_data:
  minio_data:

networks:
  boilerplate_network:
    driver: bridge
